# Site settings
title: Danny DeBelius
email: danny.debelius@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Danny DeBelius is an editor, designer and developer at The New York Times.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dannydebelius.com" # the base hostname & protocol for your site
instagram_username:
facebook_username:
flickr_username:
twitter_username: dannydb
github_username:  dannydb
linkedin_username: dannydebelius
lastfm_username: 

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
